controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Articles;
use app\models\Catalogcenters;
use app\models\Authors;
use app\models\Catalogsubjects;
use app\models\RegistrationForm;
use app\models\ConstructorForm;
use yii\web\UploadedFile;
use App\Http\Requests;
use yii\web\Request;
class SiteController extends Controller
{
    public $stringImage;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
              'only' => ['ajax-login','addarticle','registration'],
                'rules' => [
                    [
                        'actions' => ['addarticle'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
             [
                        'allow' => true,
                        'actions' => ['ajax-login', 'registration'],
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function beforeAction($action) {
    if ($action == 'redirect') {
        $this->enableCsrfValidation = false;
    }
    return parent::beforeAction($action);
}
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
         $session = Yii::$app->session;
// первый вариант
                        $session->set('imgString',  "/images/noimage.png");
        $articles = Articles::find()->where(['Id_catalogArticlesType' => 1])->limit(3)->orderBy('DateOfCreation DESC, Id DESC')->all();
        $centers = CatalogCenters::find()->all();
        return $this->render('index', ['articles' => $articles, 'centers' => $centers]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
  public function actionAjaxLogin() {
    if (Yii::$app->request->isAjax) {
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->login()) {
                return $this->goBack();
            } else {
                Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
                return \yii\widgets\ActiveForm::validate($model);
            }
        }
    } else {
        throw new \yii\web\HttpException(404 ,'Page not found');
    }
}
      public function actionValidateRegistration() {
          $model = new RegistrationForm();
                  if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

}
      public function actionRegistration() {
        $model = new RegistrationForm();
    $request = Yii::$app->getRequest();
    if ($request->isPost && $model->load($request->post()) && $model->validate()) {
       
        //сохранение данных в бд 
           $model->registrationUser();
           return $this->render('about');

        }
            
        return $this->goBack();

      

      }
    public function actionAddarticle() {
        $type = Yii::$app->request->get('type','articles');
        $model = new ConstructorForm();
        $strImage = "";
        if ($model->load(Yii::$app->request->post())) {
         
             if ($model->validate()) {

                if ($type == 'news') {
                    $type1 = 2;
                } else {
                    $type1 = 1;
                }
                                          $session = Yii::$app->session;

                 $model->saveArticle($type1,$session->get('imgString'));
                $session->set('imgString',  "/images/noimage.png");

                return $this->render('about');
             }
         }
        return $this->render('constructor',['model'=> $model, 'type' => $type]);
    }
    public function actionFileUpload() {
         $model = new ConstructorForm();

        if (Yii::$app->request->isAjax) {
            $type = Yii::$app->request->post('type');
            $model->image = UploadedFile::getInstances($model, 'image');
            if ($model->image!=null) {
                     foreach ($model->image as $file) {

                $name_image = uniqid().'.';
                $path = Yii::$app->params['pathUploads'] . 'images/'.$type.'/'.$name_image;
                $file->saveAs($path.$file->extension);
                 $name_image = $name_image.$file->extension;
                         $session = Yii::$app->session;
// первый вариант
                        $session->set('imgString',  "/".$path.$file->extension);
//                 $project->image = $name_image;   
//                         return $this->render('constructor',['model'=> $model,'url' => 'sfdsfsd']);
                return '{"response": "'.$path.$file->extension.'"}';
            }
            }
        }
    }
    
  
    public function actionSchools() {
        $subjects = Catalogsubjects::find()->where(['Deleted' => 0])->orderBy('Order ASC')->all();
        return $this->render('schools',['subjects' => $subjects]);
    }
    public function actionArticles() {
        $request = Yii::$app->request;
        $tag = $request->get('tag',''); 
        $title = "Все статьи";
        $author1 = $request->get('author','no author'); 
        
        if ($tag!='') {
            $title.="по тегу #".$tag; 
        }
        if ($author1==='no author') {
            $articles = Articles::find()->where(['Id_catalogArticlesType' => 1])->andWhere(['like', 'Tags', $tag])->orderBy('DateOfCreation DESC, Id DESC')->all();
        } else {
            $author = Authors::findOne(['AuthorUrl' => $author1]);
            $author_name = $author->AuthorNameBy;
            $title.=" автора ".$author_name;
            $articles = Articles::find()->where(['Id_catalogArticlesType' => 1, 'AuthorId' => $author->AuthorId])->andWhere(['like', 'Tags', $tag])->orderBy('DateOfCreation DESC, Id DESC')->all();

        }

        return $this->render('articles', [
            'articles' => $articles,
            'title' => $title
        ]); 
        
    }
    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
    public function actionArticle()
    {
         $request = Yii::$app->request;
        $furl = $request->get('name',''); 
        $article = Articles::findOne(['FURL' => $furl]);
        if ($article == null) {
            return $this->render('error');
        }    
        $author = Authors::findOne(['AuthorId' => $article->AuthorId]);
        
        return $this->render('article', ['article' => $article, 'author' => $author]);
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
//    public function actionContact()
//    {
//        $model = new ContactForm();
//        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
//            Yii::$app->session->setFlash('contactFormSubmitted');
//
//            return $this->refresh();
//        }
//        return $this->render('contact', [
//            'model' => $model,
//        ]);
//    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\models\LoginFormWidget;
use app\models\RegistrationFormWidget;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
    
<?php $this->beginBody() ?>
<?= (Yii::$app->user->isGuest ? LoginFormWidget::widget([]) : ''); ?>
<?= (Yii::$app->user->isGuest ? RegistrationFormWidget::widget([]) : ''); ?>


    
    
<div class="wrap">
    <style>
    
    .fa-sign-in:before {
	content: "\f090";
	font-family: FontAwesome;

	/* more styling for the icon, including color, font-size, positioning, etc. */
}
        
    </style>
    <?php
    NavBar::begin([
        'brandLabel' => '<img src="/images/logo.png" class="logo" style="margin-top: 14px">',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-fixed-top',
        ],
    
    ]);
 $menuItems = [
            ['label' => 'Главная', 'url' => ['/site/index']],
            ['label' => 'Статьи', 'url' => ['/site/articles']],
            ['label' => 'Игры', 'url' => ['/site/schools']],
            ['label' => 'Товары', 'url' => ['/site/aboutNOKO']],
        ];
            Yii::$app->user->isGuest ? (
//                 class="text-center" data-toggle="modal" data-target="#modalLogin"><i class="fa fa-sign-in" aria-hidden="true"
            $menuItems1[] = ['label' => 'Войти', 'url' => '#', 'options' => ['data-toggle' => 'modal', 'data-target' => '#login-modal'], 'linkOptions' => ['class' => 'fa fa-sign-in', 'aria-hidden' => 'true']]

            ) : (
               $menuItems1[] =    ['label' =>Yii::$app->user->identity->login,
            'items' => [
                 ['label' => 'Добавить статью или новость', 'url' => ['site/addarticle']],
                 ['label' => 'Добавить учебное заведение', 'url' => '#'],
                 ['label' => 'Добавить образовательный центр', 'url' => '#'],
    
                 ['label' => 'Выйти', 'url' => ['/site/logout'], 'linkOptions' =>  ['data-method' => 'POST']],

            ],
        ]
                );

    echo Nav::widget([
        'options' => ['class' => 'nav navbar-nav navbar-center'],
        'items' => $menuItems
        
        
    ]);
 echo Nav::widget([
        'options' => ['class' => 'nav navbar-nav navbar-right'],
        'items' => $menuItems1
        
        
    ]);
    NavBar::end();
    ?>

        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    
    <?php
    $this->registerJs(                                   
    "$(function() {
       $('#modalButton a').click(function(e) {
       e.preventDefault();
       $('#modalLarge').modal('show')
         .find('.modal-content')
         .load($(this).attr('href'));
      });
     });", 
yii\web\View::POS_END, 'login-modal');
    
    ?>
      <?php
    $this->registerJs(                                   
    "$(function() {
       $('#modalButton a').click(function(e) {
       e.preventDefault();
       $('#modalLarge').modal('show')
         .find('.modal-content')
         .load($(this).attr('href'));
      });
     });", 
yii\web\View::POS_END, 'registration-modal');
    
    ?>
    
  
</div>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

 <div class="footer">
      <div class="container foot_container">
        <a class=" col-lg-4 col-md-4 col-sm-4 col-xs-12 foot-logo" href="#"  ><img src="/images/logo_footer.png" class="logo"  style="margin-top: 5px"></a>
        <h4 class="col-lg-4 col-md-4 col-sm-4 col-xs-12 foot-story text-center" >BrainStory<br>&copy; 2017</h4>
        <ul class="col-lg-4 col-md-4 col-sm-4 col-xs-12 foot-social list-inline text-right" >
          <li><a href="https://vk.com/edu39"><i class="fa fa-vk fa-2x" aria-hidden="true"></i></a></li>
          <li><a href="https://facebook.com/edu39.me"><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></a></li>
          <li><a href="https://instagram.com/edu39.me"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></a></li>
        </ul>
      </div>
    </div>
<?php 
    yii\bootstrap\Modal::begin(['id'=>'modalLarge', 'size' => 'modal-lg']);
yii\bootstrap\Modal::end();

    ?>
<?php $this->endBody() ?>
</body>
</html>

<?php $this->endPage() ?>